MARCAS = [
    "Risqué",
    "Colorama",
    "Impala",
    "Hits Speciallità",
    "Dailus",
    "Vult",
    "Ana Hickmann",
    "Mohda",
    "Eliana Dote",
    "Ludurana",
    "Blant Colors",
    "DNA Italy",
    "Novo Toque",
    "Bella Brazil",
    "Beauty Color",
    "Koloss",
    "Max Beauty",
    "Top Beauty",
    "Jade",
    "Granado",
    "Jequiti",
    "Mundial Impala",
    "Passe Nati",
    "Hello Kitty",
    "Ellen Gold",
    "Realce",
    "View Cosméticos",
    "Foup",
    "B.U.",
    "Ricca",
    "Boticário",
    "Vefic",
    "Ten Beauté",
    "Luxor",
    "Haskell",
    "Panvel",
    "Preta Gil",
    "Luzzy",
    "Yenzah",
    "Alessandro",
    "Flormar",
    "Ruby Rose",
    "Mavala",
    "Kiss New York",
    "Super Pérola",
    "Latika",
    "Farmax",
    "Altamoda",
    "Tracta",
    "Kolt",
    "Lacan",
    "Alfaparf",
    "Nyce",
    "Mia Secret",
    "Cora",
    "Bellaoggi",
    "Verniz",
    "Lokenzzi",
    "Ricca",
    "Vernier",
    "Dracarys",
]
COR = [
    "Vermelho",
    "Rosa",
    "Nude",
    "Branco",
    "Preto",
    "Azul",
    "Verde",
    "Amarelo",
    "Laranja",
    "Roxo",
    "Marrom",
    "Cinza",
    "Prata",
    "Dourado",
    "Bordô",
    "Coral",
    "Turquesa",
    "Lilás",
    "Bege",
    "Rubi",
    "Taupe",
    "Pêssego",
    "Menta",
    "Ameixa",
    "Burgundy",
    "Champagne",
    "Terracota",
    "Malva",
    "Mostarda",
    "Salmão",
    "Celeste",
    "Grafite",
    "Púrpura",
    "Cobre",
    "Índigo",
    "Fúcsia",
    "Caramelo",
    "Cobalto",
    "Marsala",
    "Ocre",
    "Salmon Rose",
    "Pistache",
    "Lavanda",
    "Açaí",
    "Gelo",
    "Orquídea",
    "Rosa Millennial",
    "Verde Militar",
]